spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/dpla
    hikari:
      username: ENC() # 프로젝트 별 수정
      password: ENC() # 프로젝트 별 수정
      maximum-pool-size: 10     #최대 커넥션 수
      minimum-idle: 5           #최소 유휴 커넥션 수
      idle-timeout: 600000      #유휴 커넥션 유지 시간(밀리초)
      max-lifetime: 1000000     #커넥션 최대수명(밀리초)
      connection-timeout: 30000 #커넥션 대기시간(밀리초)

# Logging
logging:
   config: classpath:conf/log4j2-dev.xml


# Etc
serverName: DEV