name: Java CI with Maven
 
on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3          # 소스코드 checkout 단계
  
    - name: Set up JDK 17                # setup languages 단계
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: maven
         
    - name: Build with Maven            # 소스코드 빌드 단계
      run: mvn -B package --file pom.xml
 
    - name: Build Docker Image          # 컨테이너 이미지 빌드 단계
      run: docker build -t <IMAGE_NAME>:<TAG_NAME> .
  
    - name: Log in to Azure Container Registry        # Azure 로그인 단계
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
  
    - name: Tagging & Push Docker image               # push to ACR 단계
      run: |
        docker tag <IMAGE_NAME>:<TAG_NAME> ${{ secrets.AZURE_ACR_SERVER }}/<IMAGE_NAME>:<TAG_NAME>
        docker push ${{ secrets.AZURE_ACR_SERVER }}/<IMAGE_NAME>:<TAG_NAME>
  
    # - name: Clean up Docker
    #   run: docker system prune -af
